### ISSUE TITLE
Look into switching backend driver from jTDS

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#101]
[FreeTDS](http://www.freetds.org) vs [jTDS](http://jtds.sourceforge.net):
- FreeTDS still under [active development](https://github.com/FreeTDS/freetds); [jTDS is not](https://sourceforge.net/p/jtds/code/HEAD/tree/). jTDS is compliant with old versions of JRE and JDBC interfaces which are being deprecated.
- FreeTDS is C based, whereas jTDS is Java based. The latter introduces a significant performance hit (lots of data being copied between different layers) 
- FreeTDS is provides a library `libtds` which may be sufficient to build DBI-compliant backend whereas, jTDS imposes another layer of abstraction in the form of JDBC
- Haven't ever had to a link a C-based library into an R package; whereas I do know rJava and, while feature constrained, is something I understand.

See also comments #98

**Comment by Hong-Revo** [comment]
Imanuel, have you considered the Microsoft ODBC drivers? They're freely available for Windows and Linux.

https://msdn.microsoft.com/library/mt703139.aspx

I know you use a Mac, but maybe one of the downloads there will work.

**Comment by imanuelcostigan** [comment]
Or open sourced JDBC driver https://github.com/Microsoft/mssql-jdbc

**Comment by cmhh** [comment]
I would also support the inclusion of the official Microsoft driver.  I know this jTDS driver works with Sybase, which is useful, but in my work environment I can't get it to work with SQL server.  We use trusted connections almost exclusively, and on our Linux servers, authentication is via Kerberos.  So far I've only been able to connect from Linux with the official MS drivers with a connection string like the following:

```r
drv <- JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver" , "<path>/sqljdbc4.jar")
conn <- dbConnect(drv, "jdbc:sqlserver://wprdclsqlcorp10.stats.govt.nz:1433;
                  databaseName=GMS_Core;integratedSecurity=true;
                  authenticationScheme=JavaKerberos")
```

I have downloaded the `RSQLServer` package and (crudely) modified it to work with the official MS driver instead and it works great otherwise.

**Comment by imanuelcostigan** [comment]
Will go with Microsoft's JDBC driver as it is the least work at the moment. Will need to potentially compile a version of the JDBC driver that was released as [open source](https://github.com/Microsoft/mssql-jdbc/blob/master/CHANGELOG.md)

**Comment by naveennjs** [comment]
Hello, I installrd RSQSErver from github using the msft-feature-driver branch. However, I am not able to connect to my server ... however, RJDC works though!

I am using:
drv=RSQLServer::SQLServer();
Con=dbConnect(drv, user=username,password=password,host=serverinfo,port=1433,dbname=database)

is there a vignette which I can use ? 

Am I doing anything wrong here?

Error message is :

Error: unable to create connections. The tcp/up connection to host local host, port 1433 has failed....

Note that my server is on AWS.

**Comment by naveennjs** [comment]
I found why this error happens.
If I pass serverName =hostname as a parameter in dbconnect, it works...

I think there is a mismatch in the documentation vs your code. In the code where u r setting comnection property to jts object,
