### ISSUE TITLE
repeated inserts with dbWriteTable and partial data.frame

### ISSUE THREAD

**Issue by r2evans** [imanuelcostigan/RSQLServer#102]
Intention: write a subset of fields into a table. (I know in general this doesn't work, but it should fail more gracefully.)

### Expected behaviour

Either inserting provided columns (implied "nulls" for missing columns) or return an error.

### Actual behaviour

Table deleted.

If I do this with a table that previously exists, it rolls back to a previous version of the table. (Is the `doRollback` being too aggressive?)

### Steps to reproduce behaviour

```r
conn <- dbConnect(RSQLServer::SQLServer(), ...)
dbExecute(conn, "create table testtable1 (id uniqueidentifier primary key, num1 integer, num2 integer)")
# [1] 0
dbGetQuery(conn, "select * from testtable1")
# [1] id   num1 num2
# <0 rows> (or 0-length row.names)
dbWriteTable(conn, "testtable1", data.frame(num1 = 1:3, num2 = 5:7), overwrite = FALSE, append = TRUE)
# Error: execute JDBC update query failed in dbExecute: Cannot insert the value NULL into column 'id', table 'Dev.Ford.RaceRS.dbo.testtable1'; column does not allow nulls. INSERT fails.
dbGetQuery(conn, "select * from testtable1")
# Error: Unable to retrieve result set for select * from testtable1: Invalid object name 'testtable1'.
dbExistsTable(conn, "testtable1")
# [1] FALSE
```

**Comment by imanuelcostigan** [comment]
What is the corresponding behaviour for RMySQL or RSQLite?

**Comment by r2evans** [comment]
Sorry, this is a T-SQL problem, I should be creating it as `id uniqueidentifier default new sequentialid()` (after which the error does not occur).
