### ISSUE TITLE
allow for temporary tables in dbWriteTables

### ISSUE THREAD

**Issue by r2evans** [imanuelcostigan/RSQLServer#112]
`dbListTables` will not return the names of local temporary tables; there is a way to get them, but: (1) they are still mangled with the connection "spid", as in `#tablename______0000000035e3` (easy to fix); and (2) they are the names for all sessions, not necessarily accessible to the current session.

(To see the names of temporary tables for all sessions, run `dbListTables` with a catalog of `"tempdb"`.)

Unfortunately, because of this, `dbWriteTable` will not work with a temporary table. Three thoughts:
1. Argument to `dbWriteTable` an argument like `check_exists = TRUE`; defaulting to true, if false then the user has knowingly taken the chance that it may fail if the table does not really exist.
2. Crack the nut on how the ending "spid" is concocted, internally filter for correct ones, and returned the de-mangled names. This is hugely problematic: I cannot find a clear definition of how this is defined.
3. Add an argument to `dbListTables` that returns all de-mangled names regardless of session owner. This will be problematic: (1) it is metadata about other processes (I'm surprised MS even allows it, frankly); and (2) just because a temp table is listed does not mean it is accessible.

(I'm really surprised that T-SQL and jTDS provide no ability to list current-session temp tables, and I know of no workaround.)

**Comment by imanuelcostigan** [comment]
See #29, #41 and #75 and PR #79 for history on this. NB: that MySQL has the same issues.
