### ISSUE TITLE
Time Zone is always UTC

### ISSUE THREAD

**Issue by shrektan** [imanuelcostigan/RSQLServer#115]
@imanuelcostigan Thanks for this great package. We find it very useful for us. However, I would like to report a bug in the dev version due to the timezone setting.

For datetime columns, the dev version of `RSQLServer` will always return date with timezone `UTC`, which is not consistent with the previous behavior. 
### Expected behaviour

The `timezone` should be consistent with what's returned in `RODBC` as well as the CRAN version of `RSQLServer`
### Actual behaviour

Now, all the datetime object is in timezone `UTC`. As below:

``` r
sql <- "select max(Update_Time) as Time from CORE_Data_Holding where Date = '2016-09-23'"

# use RODBC
myconn <- activate_conn(myconn)
sqlQuery(myconn, sql)$Time
## [1] "2016-09-26 12:21:15 CST"

# use the CRAN version of RSQLServer
db_mo <- activate_conn(db_mo)
DBI::dbGetQuery(db_mo, sql)$Time
## [1] "2016-09-26 12:21:15 CST"

# use dev version of RSQLServer
db_mo <- activate_conn(db_mo)
DBI::dbGetQuery(db_mo, sql)$Time
## [1] "2016-09-26 12:21:15 UTC"
```
### Steps to reproduce behaviour
1. set up a sqlserver with default timezone is not `UTC`
2. create a new table with datetime type column
3. read from that table via `RODBC`, CRAN version of `RSQLServer`, current dev version of `RSQLServer`

you will find the first two timezone would not be `UTC` while the last one is `UTC`

**Comment by shrektan** [comment]
Sorry, I tested it in a Linux machine (previously, it was a windows machine), and find out the returned timezone is `UTC` even for `CRAN` version of `RSQLServer`.

So, the `timezone` info via the steps above might not be the timezone that in SQLServer. The SQLServer  itself might don't even record the `timezone` info.

You can close this issue if you think my presume is right. Thanks a lot.

**Comment by shrektan** [comment]
But I just tested for a Oracle database using `ROracle` and find:

1. for `datetime` field, the timezone that returned is different for windows and Linux. 
1. In windows, since I'm in China, the result is like `2016-09-27 09:27:48 CST` while in Linux is `2016-09-27 09:27:48 UTC`
1. So, the timzeone info there is not from the database. Instead, it's the timezone info in the client machine.

However, the `ROracle`, `RODBC`, `CRAN version of RSQLServer` behaves the same as described above, while the dev version of `RSQLServer` behaves differently (Although I think it's better, since in all platform it returns UTC).  

So, I'll leave the question to you :smile:  

Thanks again.

**Comment by imanuelcostigan** [comment]
Might have to wait until #101
