### ISSUE TITLE
Release v0.3 to CRAN

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#117]
- [X] Waiting for hadley/dplyr#1997 to be merged.
- [x] Waiting for dev version of dplyr (and first version of dbplyr) to be released to CRAN

**Comment by DanielFerrazCampos** [comment]
Sorry if I am repeating something here, I could not find the answer elsewhere.

Is this issue going to be solved soon? Which workarounds has been done?

**Comment by Hong-Revo** [comment]
There has been activity on https://github.com/hadley/dplyr/pull/1997 in the last week, so hopefully this will be resolved soon. In the meantime, if this is preventing you working with RSQLServer, there are a couple of options:

* Install dplyr 0.4.3. This is most easily done via the MRAN snapshot archive:
```
install.packages("dplyr", repos="https://mran.revolutionanalytics.com/snapshot/2016-04-30")
install.packages("RSQLServer", repos="https://mran.revolutionanalytics.com/snapshot/2016-04-30")
```
* Install the dev version of RSQLServer, which will also install a patched dplyr 0.5. Both of these will be installed _from source_:
```
devtools::install_github("imanuelcostigan/RSQLServer")
```
For the latter, if you're on Windows you'll also need to install the [R tools for Windows](https://cran.r-project.org/bin/windows/Rtools/) collection which includes the gcc compiler and several other ported Unix utilities.

**Comment by imanuelcostigan** [comment]
Change reference to master branch of dplyr: fef3c27

**Comment by imanuelcostigan** [comment]
Possible March release of updated dplyr: https://github.com/hadley/dplyr/pull/2013#issuecomment-270145507

**Comment by imanuelcostigan** [comment]
Submitted v0.3.0 to CRAN

**Comment by imanuelcostigan** [comment]
And now re-released....https://cran.r-project.org/web/packages/RSQLServer/index.html
