### ISSUE TITLE
Unexpected response when the wrong password is used.

### ISSUE THREAD

**Issue by jonkeane** [imanuelcostigan/RSQLServer#118]
### Expected behaviour

When authenticating with a wrong password, the error should if possible reference a password or username/password combination problem.
### Actual behaviour

Currently, when I enter a wrong password I get the error:

```
java.sql.SQLException: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
```

When I first got this error, I suspected that something more than just the password was wrong, after some troubleshooting, with different domain specifications and NTLM settings, I discovered that this is the same error that is thrown when a wrong password is entered. I'm not sure if this is just the error that jTDS throws and therefor not truly a bug in RSQLServer, but I was thrown off by it's content when troubleshooting.
### Steps to reproduce behaviour

Try to authenticate with an incorrect password:

``` r
dbConnect(SQLServer(), "[server url]",
    properties=list(useNTLMv2=TRUE,
    domain="[domain name]",
    user="[username]",
    password="[an incorrect password]")
)
```

R version: 3.2.5, RStudio: 0.99.896, DBI 0.3.1, RJDBC 0.2-5, RSQLServer 0.2.0 (all from CRAN)

**Comment by imanuelcostigan** [comment]
This error is served up by the underlying driver which I am not maintaining.
