### ISSUE TITLE
Unable to load library

### ISSUE THREAD

**Issue by eddargan** [imanuelcostigan/RSQLServer#119]
### Expected behaviour

library(RSQLServer) completes successfully and module can be used

### Actual behaviour

Instead, I get the following error message: 

Loading required package: DBI
Error : object ‘src_translate_env’ is not exported by 'namespace:dplyr'
Error: package or namespace load failed for ‘RSQLServer’

### Steps to reproduce behaviour
Install Package and then attempts to load using library function

**Comment by imanuelcostigan** [comment]
Use the dev version of the package rather than the version on CRAN: `devtools::install_github("imanuelcostigan/RSQLServer")`.
