### ISSUE TITLE
awful performance with big tables

### ISSUE THREAD

**Issue by bluaze** [imanuelcostigan/RSQLServer#12]
when create tbl with tables more than millions of rows, it needs a long time to get tbl object returned. it's unreasonable and after profiling the source code, i found the S3 method db_query_fields.SQLServerConnection ate most of the time consumed, which in turn spent most of the time on "dbSendQuery(con, paste0("SELECT * FROM ", sql)".
it might be more reasonable to add "WHERE 0=1" or something similar to the end of the query to be sent, just like the db_query_fields method for DBIConnection.
printing tbl of big tables are also time consuming, but i havn't profiled them thoroughly.

**Comment by imanuelcostigan** [comment]
Thanks! Are you able to send a pull request?

**Comment by imanuelcostigan** [comment]
dplyr functions are being removed from this branch with potential integration directly into dplyr. See: 
https://groups.google.com/d/topic/manipulatr/9QrAEMt-9jc/discussion

**Comment by imanuelcostigan** [comment]
Without `WHERE 0 = 1` clause (for 200k row table)

```
   user  system elapsed 
   0.40    0.35    9.58 
```
With "WHERE 0 = 1" clause (for same table):

```
    user  system elapsed 
   0.34    0.04    4.23 
```

**Comment by imanuelcostigan** [comment]
See also #17
