### ISSUE TITLE
dplyr::arrange results in only 100 rows being returned

### ISSUE THREAD

**Issue by NikNakk** [imanuelcostigan/RSQLServer#124]
### Expected behaviour

`dplyr::arrange` should change the order of results but not introduce a limit

### Actual behaviour

The fix for issue #49 means that only a maximum of 100 rows will be returned once `arrange` is used.

### Steps to reproduce behaviour

```
library(dplyr)
db <- RSQLServer::src_sqlserver("SQL_PROD")
# Imagine table 'people' has 240 rows
tbl(db, "people") %>% collect %>% nrow
# 240
tbl(db, "people") %>% arrange(Name) %>% collect %>% nrow
# 100
```

**Comment by imanuelcostigan** [comment]
@NikNakk can you please check whether a6c35a0 fixes this for you?
