### ISSUE TITLE
dplyr does not request data from tables lazily as expected/needed

### ISSUE THREAD

**Issue by juliasilge** [imanuelcostigan/RSQLServer#132]
### Expected behaviour

Using dplyr with databases should only pull down the first 10 rows (unless using `collect()`), as [described here under "Laziness"](https://cran.r-project.org/web/packages/dplyr/vignettes/databases.html#laziness).

### Actual behaviour

The fix for #129 caused a call to a table to try to pull down the entire table instead of the first 10 rows. The commit before this fix functions as expected but all the ones after are malfunctioning.

### Steps to reproduce behaviour

```
library(dplyr)
db <- RSQLServer::src_sqlserver("SQL_PROD")

## normally, the following command should only pull down 10 rows
tbl(db, "people")
## instead, it is pulling down the entire table before printing the results

## even if you try this:
tbl(db, "people") %>% 
    head(10)
## it will attempt to pull down the entire table before doing head()
```

**Comment by imanuelcostigan** [comment]
Thanks for reprex - should be fixed now.

**Comment by juliasilge** [comment]
Thanks so much! This is working great now.
