### ISSUE TITLE
Filtering nvarchar columns with unicode

### ISSUE THREAD

**Issue by refik** [imanuelcostigan/RSQLServer#136]
### Expected behaviour
When a table is to be filtered based on an `nvarchar` column with a unicode string, prefixing the sql `WHERE` clause value with an `N`.

### Actual behaviour
The prefix is not added so the query doesn't work as expected.

### Steps to reproduce

```
> dplyr::filter(table, tests_column == "ünicöğde") %>% explain()
<SQL>
SELECT  *
FROM "TEST_TABLE"
WHERE "test_column" = 'ünicöğde'
```

Even if there are rows that have `test_column` with the value `ünicöğde`, this query returns no rows. Even when it is run on SQL server management studio. However, when the value if prefixed with an `N`, it works.

```
SELECT  *
FROM "TEST_TABLE"
WHERE "test_column" = N'ünicöğde'
```

This behaviour is [explained here](https://msdn.microsoft.com/en-IN/library/ms186939.aspx)

> Prefix Unicode character string constants with the letter N. Without the N prefix, the string is converted to the default code page of the database. This default code page may not recognize certain characters.

**Comment by imanuelcostigan** [comment]
This is a known issue: https://github.com/rstats-db/DBItest/issues/77

**Comment by refik** [comment]
Oh I see. I would be willing to fork the repo and use a temporary work around that only works for my case. Can I get a few pointers as to how it could be done? I was considering making a change [here](https://github.com/imanuelcostigan/RSQLServer/blob/master/R/sql-backends.R#L56)

**Comment by refik** [comment]
@imanuelcostigan could there be a way to get this behaviour with something like this? I couldn't make it work though.

```
dplyr::filter_(table, translate_sql(`test_column = N'ünicöğde'`)
```

**Comment by refik** [comment]
In the meantime, this works: `dplyr::filter(table, test_column == sql("N'ünicöğde'"))`
