### ISSUE TITLE
Cross database joins without `copy = TRUE`

### ISSUE THREAD

**Issue by refik** [imanuelcostigan/RSQLServer#139]
### Expected behaviour
Being able to do cross database joins without copying tables from one database to the other if databases are on the same server.

### Actual behaviour
Even though two databases can be queried from the same connection (thus same `src_sqlserver`), there is no way (that I've found) to create `tbl_sqlserver`'s that uses the same `src_sqlserver`, but different databases. 

The only way to do such joins is creating seperate `src_sqlserver` for each database.  In case of a join between these tables, `dplyr` complains:
```
Error: x and y don't share the same src. Set copy = TRUE to copy y into x's source (this may be time consuming).
```

When `copy = TRUE`, a temporary table is created on the SQL Server. In my case this brings `collation` issues and I can't specify the collation for the temporary table and I can't change the default collation of the server. 

### Steps to reproduce behaviour
```
conn_1 <- RSQLServer::src_sqlserver(server = "prod", database = "db1")
conn_2 <- RSQLServer::src_sqlserver(server = "prod", database = "db2")
tbl_1 <- dplyr::tbl(conn_1, "table_1")
tbl_2 <- dplyr::tbl(conn_2, "table_2")
dplyr::left_join(tbl_1, tbl_2, by = "column")
```

I suspect this is a general issue about working with `dplyr` but I wanted to put it out here anyway. Maybe something could be done.

**Comment by refik** [comment]
My best bet was using `dplyr::sql` but it failed because for some reason the raw sql gets wrapped around in parenthesis. 

```
> dplyr::tbl(conn_1, dplyr::sql("[db1].[dbo].[table_1]"))
Error: Unable to retrieve result set for SELECT  *
FROM ([db1].[dbo].[table_1]) "zzz35"
WHERE 0 = 1: Incorrect syntax near ')'.
```

**Comment by refik** [comment]
@imanuelcostigan I'm curious about your take on this. Is this a reasonable thing to expect from RSQLServer?

**Comment by imanuelcostigan** [comment]
@refik can you confirm behaviour of one or two different backends (e.g. SQLite, MySQL, etc)

**Comment by refik** [comment]
No backend does this so I'm closing this issue
