### ISSUE TITLE
Error on dbWriteTable when any value is NA

### ISSUE THREAD

**Issue by refik** [imanuelcostigan/RSQLServer#140]
### Expected behaviour
Being able to insert data with `NA` columns, converted to MSSQL `NULL`.

### Actual behaviour
An `rJava` error.

### Steps to reproduce behaviour
```
> RSQLServer::dbWriteTable(con, "test_table", data.frame(x = c(1,2,3,NA)))
Error in rJava::.jcall(ps, "V", "setNull", i, jtype) : 
  method setNull with signature (ID)V not found
```

**Comment by jkaupp** [comment]
I am also encountering this behaviour. Steps to reproduce are similar

**Comment by leoluyi** [comment]
Same issue here

**Comment by harrismcgehee** [comment]
I still get an error when I run the reprex in the original post.
```
> RSQLServer::dbWriteTable(conn, "test_table", data.frame(x = c(1,2,3,NA)))
Error in rJava::.jcall(ps, "V", "setNull", i, jtype) : 
  method setNull with signature (ID)V not found
```
Just reinstalled.
sessionInfo() includes `RSQLServer_0.2.099`
DESCRIPTION contains `RemoteRef: master
RemoteSha: ec9226ff7658c905352070876ecb9d6be61453e3`

What else can I do to help diagnose?
