### ISSUE TITLE
dbGetQuery method?

### ISSUE THREAD

**Issue by cdeterman** [imanuelcostigan/RSQLServer#141]
### Expected behaviour
Given this package is a `DBI` extension I would expect to see other functions that I see in others such as `ROracle` and `RPostgreSQL`.  I would therefore expect to find the `dbGetQuery` function exported.

### Actual behaviour
I don't find the `dbGetQuery` function exported.

### Steps to reproduce behaviour
Install directly from this github repository. No such function is available.

**Comment by imanuelcostigan** [comment]
The DBI package comes with an implementaiton of the dbGetQuery generic. There is no need for this package to supply same. 

If you are loading the RSQLServer library, you are doing it wrong. See the README for usage.
