### ISSUE TITLE
purrr::map_if is now deprecated in favor of purrr::modify_if

### ISSUE THREAD

**Issue by r2evans** [imanuelcostigan/RSQLServer#148]
Hadley has [deprecated `map_if`](https://github.com/tidyverse/purrr/blame/32a4089db1d9d5404bfb9380b5dd8fb30f9690aa/R/modify.R#L140) in the github version of `purrr`. Either need to update to `modify_if` or lock to a reference of `purrr`. (I suggest the former.)

**Comment by imanuelcostigan** [comment]
I've set this for correction with v0.3 on assumption that new version of purrr will be released alongside the next version of dplyr. While we wait for these to be released to CRAN, will need to make sure that things work. So perhaps dev version of this package needs to lock on a dev version of purrr (like dplyr) and make necessarily changes to purrr calls. Would you be able to submit a PR?

**Comment by r2evans** [comment]
I'll see if I can work on it ... after I figure out what the difference is, haven't looked at it at all. (I'll be happier when the specific refs in `dplyr` and `purrr` can go away. In the meantime, either I manually roll back `purrr` to 20 days ago, use `suppressWarnings` to all of my calls to your package, or deal with a screen-full of warnings. Yuck.)

**Comment by imanuelcostigan** [comment]
Looks like `map_if()` will be supported for a least this next dot release (maps to `modify_if()` with a warning. So no need to address this with v0.3 of RSQLServer at this stage.

**Comment by r2evans** [comment]
Just realized that recent changes to `dplyr` have made it not stable/usable for me, so I have to downgrade to a Jan-2017 reference so that my code doesn't crash R. Unless/until I'm able to provide a good reproducible issue for Hadley for that problem, it'll be a bit difficult to work on this PR. Good thing it isn't an urgent fix. I'll check back later if/when I'm able to upgrade.

Thanks!
