### ISSUE TITLE
Collation error

### ISSUE THREAD

**Issue by refik** [imanuelcostigan/RSQLServer#155]
I'm trying to join an external data with a table in SQL Server. In order to do so, I use `copy = TRUE` on `dplyr::left_join` and copy the external data to SQL Server. My servers default collation is `Turkish_CI_AS` and changing it is not an option.  I think because of this, temporary table created in result of `copy = TRUE` uses that collation. However the default collation of my user database is `SQL_Latin1_General_CP1_CI_AS`. 

Since these collations are different, I get an error whenever I try to join with an external data source. Majority of my data is in SQL server and `collect()`ing it just to join would be very inefficient. 

The solution I've found on the internet was to use `COLLATE` clause on join like this:
`SELECT * FROM A JOIN B ON A.Text = B.Text COLLATE SQL_Latin1_General_CP1_CI_AS `

I couldn't find a way to apply this solution to `dplyr` interface. Any help would be appreciated.

This is my error:
```
  FULL JOIN "#oacsjjuffd" AS "TBL_RIGHT"
  ON ("TBL_LEFT"."account_number" = "TBL_RIGHT"."account_number")
: Cannot resolve the collation conflict between "Turkish_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the equal to operation.
```

**Comment by imanuelcostigan** [comment]
@refik would this be unique to SQL Server or would you see this behaviour with all backends? If the latter, then suggest better place for this issue would be rstats-db/DBI.

**Comment by refik** [comment]
I don't know, its hard to set that up and doesn't solve the problem. I don't think its purely a DBI issue either since it is the dplyr interface I am using and the solution requires manual intervention. If there are no suggestions then this issue can be closed.

**Comment by refik** [comment]
I was able to solve the with issue with this commit: https://github.com/AudioElektronik/RSQLServer/commit/a56381320c3b74e6a99319112643caed84f1c8f3

I didn't apply it to the latest development version because issue https://github.com/imanuelcostigan/RSQLServer/issues/154 prevents me from using the latest version.

@imanuelcostigan should I make a pull request for this later?
