### ISSUE TITLE
Plans to re-submit to CRAN?

### ISSUE THREAD

**Issue by levithatcher** [imanuelcostigan/RSQLServer#159]
Love the package, and would love to not have to download from github.

Can I help with particular issues?

**Comment by imanuelcostigan** [comment]
Thanks @levithatcher. I will be looking to resubmit v0.3 to CRAN (see #117) once v0.6 of dplyr is released on CRAN. This is expected to [happen mid May](https://blog.rstudio.org/2017/04/13/dplyr-0-6-0-coming-soon/)

**Comment by levithatcher** [comment]
Thanks! Do you anticipate such downtime from CRAN again in the future or will things be stable after May?

**Comment by imanuelcostigan** [comment]
No was down because a previous dplyr release broke things irredeemably. I hope this won't happen again.

**Comment by levithatcher** [comment]
Awesome, thanks Imanuel! If there are things you need help with, please don't hesitate. We may use your work in our healthcare machine learning package: https://github.com/HealthCatalystSLC/healthcareai-r

**Comment by benjaminrobinson** [comment]
Any updates on planning to resubmit to CRAN?

**Comment by refik** [comment]
@benjaminrobinson dplyr v0.6 hasn't arrived yet. You can check from here: https://cran.r-project.org/web/packages/dplyr/index.html

**Comment by benjaminrobinson** [comment]
@hadley Do you know when dplyr v0.6 will be released?  Just wondering.  Thanks!

**Comment by hadley** [comment]
It is still in the CRAN submission process.

**Comment by benjaminrobinson** [comment]
Thanks for the update, @hadley!

**Comment by Hong-Revo** [comment]
[Looks like it's just appeared on CRAN.](https://cran.r-project.org/web/packages/dplyr/index.html)
