### ISSUE TITLE
Creating tbl on non-default DB and Schema Fails

### ISSUE THREAD

**Issue by schnee** [imanuelcostigan/RSQLServer#162]
(I'm not sure if this is RSQLServer, DBI, or a tidyverse problem)

### Setup
library(DBI)
library(dplyr)
library(dbplyr)
conn <-
  dbConnect(RSQLServer::SQLServer(),
            server = "server",
            database = "DW")

### Expected behaviour
v1 <- tbl(conn, "vw_view1")
v2 <- tbl(conn, "db.schema.vw_view2")

both v1 and v2 should be created

### Actual behaviour
At the v2 call, I get

Error: Unable to retrieve result set for SELECT  *
FROM "db.schema.vw_view2" AS "zzz4"
WHERE 0 = 1: Invalid object name 'db.schema.vw_view2'.

### Steps to reproduce behaviour
define above

### SessionInfo
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-05-24                  

Packages -------------------------------------------------------------------------------------------
 package    * version    date       source                                     
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.0)                             
 curl         2.6        2017-04-27 CRAN (R 3.4.0)                             
 DBI        * 0.6-1      2017-04-01 CRAN (R 3.4.0)                             
 dbplyr     * 0.0.0.9001 2017-05-24 Github (hadley/dbplyr@cf6e0a6)             
 devtools     1.12.0     2016-12-05 CRAN (R 3.4.0)                             
 digest       0.6.12     2017-01-27 CRAN (R 3.4.0)                             
 dplyr      * 0.5.0.9004 2017-05-24 Github (hadley/dplyr@f12d245)              
 git2r        0.18.0     2017-01-01 CRAN (R 3.4.0)                             
 glue         1.0.0.9000 2017-05-24 Github (tidyverse/glue@548096b)            
 httr         1.2.1      2016-07-03 CRAN (R 3.4.0)                             
 knitr        1.15.1     2016-11-22 CRAN (R 3.4.0)                             
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                             
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                             
 purrr        0.2.2.2    2017-05-11 cran (@0.2.2.2)                            
 R6           2.2.1      2017-05-10 cran (@2.2.1)                              
 Rcpp         0.12.11    2017-05-22 cran (@0.12.11)                            
 rJava        0.9-8      2016-01-07 cran (@0.9-8)                              
 rlang        0.1.1.9000 2017-05-24 Github (tidyverse/rlang@67f492d)           
 RSQLServer * 0.2.099    2017-05-24 Github (imanuelcostigan/RSQLServer@7fad668)
 tibble       1.3.1      2017-05-24 Github (tidyverse/tibble@5c183c3)          
 withr        1.0.2      2016-06-20 CRAN (R 3.4.0)                             
 yaml         2.1.14     2016-11-12 cran (@2.1.14)

**Comment by imanuelcostigan** [comment]
DBI: https://github.com/rstats-db/DBI/issues/24. See also #52
