### ISSUE TITLE
src_sqlserver' is not an exported object from 'namespace:RSQLServer

### ISSUE THREAD

**Issue by maybeth** [imanuelcostigan/RSQLServer#167]
### Expected behaviour
No error
### Actual behaviour
Hi I am getting the following error, when I submitted commands shown in section "steps to reproduce behavior" at RGui prompt
Error: 'src_sqlserver' is not an exported object from 'namespace:RSQLServer'
### Steps to reproduce behaviour
I have used following R commands:
library(dplyr)
conn<-RSQLServer::src_sqlserver("servername”, database="database name or initial catalog") 
I also installed related packages by submitting following commands 
1)	install.packages(‘devtools’)
2)	install.packages("RSQLServer")
3)	Next to get, integrated (NTLM) authentication to work, I followed steps from this site https://www.r-bloggers.com/accessing-mssql-server-with-r-rsqlserver-with-dplyr/
Download jtds-drivers and follow these instructions.
Copied ntlmauth.dll to location C:\Program Files\Java\jre1.8.0_131\bin
Copied from Downloads >>> jtds-1.3.0-dist.zip >>> x64 >>> SSO >>> ntlmauth.dll

4)	I am not sure what the purpose of step 3 is, but I did it anyway..just in case. I do not have a good understanding of what all is needed
Here is what I am trying to do.. I have a very large set, couple of million records. In interest of better performance, I do not want first to create a *.csv file from a SQL Select statement and then create a R dataframe from *.csv file. I would rather straight work with the data in the SQL Server database.
Help will be much appreciated. Thanks

**Comment by Hong-Revo** [comment]
What versions of dplyr and RSQLServer are you using?

**Comment by maybeth** [comment]
I am not sure. I am using 3.4.1 version for R. Please let me know how I can check the version of dplyr & RSQLServer. I just installed these today, using the commands 
install.packages(‘devtools’)
install.packages("RSQLServer")

So I would think whatever version one gets by submitting those commands, are the versions I got. But I can check and get back to you if you let me know how to. I am new to R.

**Comment by maybeth** [comment]
@

**Comment by maybeth** [comment]
Also, I used US OR as the mirror site

**Comment by imanuelcostigan** [comment]
```R
packageVersion("RSQLServer")
packageVersion("dplyr")
```

**Comment by maybeth** [comment]
> packageVersion("RSQLServer")
[1] ‘0.3.0’
> packageVersion("dplyr")
[1] ‘0.7.1’

**Comment by imanuelcostigan** [comment]
This is expected (albeit undocumented in release notes - sorry). dplyr's mechanism for connecting to servers has changed with 0.7. Instead of 

```R
library(dplyr)
conn<-RSQLServer::src_sqlserver("servername”, database="database name or initial catalog")
```

You do the following  

```R
library(DBI)
library(dplyr)
dbi_conn<-dbConnect(...) 
```

Then use dbi_conn wherever you would have used `conn` as per above.

**Comment by Hong-Revo** [comment]
There is also an example of how to connect on the repo's front page.

```r
library(DBI)
con <- dbConnect(RSQLServer::SQLServer(), server = "TEST", database = 'DBItest')
dbWriteTable(con, "band_members", dplyr::band_members)
dbWriteTable(con, "band_instruments", dplyr::band_instruments)
# RSQLServer only returns tables with type TABLE and VIEW.
dbListTables(con)
#> [1] "band_instruments" "band_members"
dbReadTable(con, 'band_members')
#>   name    band
#> 1 Mick  Stones
#> 2 John Beatles
#> 3 Paul Beatles
dbListFields(con, 'band_instruments')
#> [1] "name"  "plays"

# Fetch all results
res <- dbSendQuery(con, "SELECT * FROM band_members WHERE band = 'Beatles'")
dbFetch(res)
#>   name    band
#> 1 John Beatles
#> 2 Paul Beatles
dbClearResult(res)
#> [1] TRUE
```

**Comment by maybeth** [comment]
Thank you
