### ISSUE TITLE
Temporary tables not cleaned up

### ISSUE THREAD

**Issue by patrick-praher** [imanuelcostigan/RSQLServer#169]
Hi,

I don't know if this is the right place to ask/report this problem, but I use RSQLServer in combination with dplyr in a Shiny app. It works great for me (thanks a lot Imanuel) except that many temporary tables are created in my DB are not cleaned up. I use dbDisconnect(...) to close the connection at the end of a session. Are there any additional steps necessary to clean up the tables or is this a bug?

Cheers
Patrick

**Comment by refik** [comment]
I don't know if you are using it but there is a bug in `dbWriteTable`. It doesn't take the `temporary` argument into consideration. However, if you add a hash in front of the table name you want to create and call the function like this:

```
dbWriteTable(conn, "#tablename", iris)
```

It works properly and the table is created as a temporary table.

**Comment by patrick-praher** [comment]
No I'm not using dbWriteTable and I don't create this tables on purpose. 
I'm using dplyr to create a "complex" query with joins ...
When I print the query with dplyr::explain it looks like this:

SELECT "TBL_LEFT"."Hash" AS "Hash", "TBL_LEFT"."Serial" AS "Serial", "TBL_LEFT"."DeviceId" AS "DeviceId", "TBL_LEFT"."ActivityType" AS "ActivityType", "TBL_LEFT"."NewState" AS "NewState", "TBL_LEFT"."Timestamp" AS "Timestamp", "TBL_LEFT"."Partition_column" AS "Partition_column", "TBL_RIGHT"."Id.dev" AS "Id.dev", "TBL_RIGHT"."Type.dev" AS "Type.dev", "TBL_RIGHT"."SerialNumber" AS "SerialNumber", "TBL_RIGHT"."Type.cap" AS "Type.cap", "TBL_RIGHT"."Name.dev" AS "Name.dev"
  FROM (SELECT  *
FROM (SELECT  *
FROM "DeviceActivityLog"
WHERE "ActivityType" = 0.0) "axfxefxkao"
WHERE "Serial" = '1234') "TBL_LEFT"
  INNER JOIN "oguewnirry" AS "TBL_RIGHT"
  ON ("TBL_LEFT"."DeviceId" = "TBL_RIGHT"."Id.cap")

The last temporary table "oguewnirry" is not deleted from my DB automatically.

**Comment by refik** [comment]
This is most likely a bug somewhere because that table name should have been `#oguewnirry` for SQL Server to treat it as a temporary table and delete at the end of the connection. Can you send `devtools::session_info()`

**Comment by patrick-praher** [comment]
Session info --------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  German_Austria.1252         
 tz       Europe/Berlin               
 date     2017-07-12                  

Packages ------------------------------------------------------------------------------------------------------------
 package    * version date       source                           
 assertthat   0.2.0   2017-04-11 CRAN (R 3.3.3)                   
 bindr        0.1     2016-11-13 CRAN (R 3.3.2)                   
 bindrcpp   * 0.2     2017-06-17 CRAN (R 3.3.3)                   
 cellranger   1.1.0   2016-07-27 CRAN (R 3.3.3)                   
 colorspace   1.3-2   2016-12-14 CRAN (R 3.3.3)                   
 DBI          0.6-1   2017-04-01 CRAN (R 3.3.3)                   
 dbplyr       1.1.0   2017-06-27 CRAN (R 3.3.3)                   
 devtools     1.12.0  2016-06-24 CRAN (R 3.3.2)                   
 digest       0.6.12  2017-01-27 CRAN (R 3.3.3)                   
 dplyr      * 0.7.1   2017-06-22 CRAN (R 3.3.3)                   
 ggplot2    * 2.2.1   2016-12-30 CRAN (R 3.3.3)                   
 glue         1.1.1   2017-06-21 CRAN (R 3.3.3)                   
 gtable       0.2.0   2016-02-26 CRAN (R 3.3.2)                   
 htmltools    0.3.5   2016-03-21 CRAN (R 3.3.2)                   
 httpuv       1.3.3   2015-08-04 CRAN (R 3.3.2)                   
 jsonlite     1.4     2017-04-08 CRAN (R 3.3.3)                   
 labeling     0.3     2014-08-23 CRAN (R 3.3.2)                   
 lazyeval   * 0.2.0   2016-06-12 CRAN (R 3.3.2)                   
 lubridate  * 1.6.0   2016-09-13 CRAN (R 3.3.2)                   
 magrittr   * 1.5     2014-11-22 CRAN (R 3.3.2)                   
 memoise      1.1.0   2017-04-21 CRAN (R 3.3.3)                   
 mime         0.5     2016-07-07 CRAN (R 3.3.2)                   
 munsell      0.4.3   2016-02-13 CRAN (R 3.3.2)                   
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.3.3)                   
 plyr         1.8.4   2016-06-08 CRAN (R 3.3.2)                   
 purrr        0.2.2.2 2017-05-11 CRAN (R 3.3.3)                   
 R6           2.2.1   2017-05-10 CRAN (R 3.3.3)                   
 Rcpp         0.12.11 2017-05-22 CRAN (R 3.3.3)                   
 readxl     * 1.0.0   2017-04-18 CRAN (R 3.3.3)                   
 reshape2   * 1.4.2   2016-10-22 CRAN (R 3.3.2)                   
 rJava        0.9-8   2016-01-07 CRAN (R 3.3.2)                   
 rlang        0.1.1   2017-05-18 CRAN (R 3.3.3)                   
 RSQLServer * 0.3.0   2017-06-17 CRAN (R 3.3.3)                   
 scales     * 0.4.1   2016-11-09 CRAN (R 3.3.2)                   
 shiny      * 1.0.2   2017-04-18 CRAN (R 3.3.3)                   
 stringi      1.1.5   2017-04-07 CRAN (R 3.3.3)                   
 stringr      1.2.0   2017-02-18 CRAN (R 3.3.3)                   
 tibble       1.3.3   2017-05-30 Github (tidyverse/tibble@b2275d5)
 tidyr      * 0.6.1   2017-01-10 CRAN (R 3.3.3)                   
 withr        1.0.2   2016-06-20 CRAN (R 3.3.2)                   
 xtable       1.8-2   2016-02-05 CRAN (R 3.3.2)
