### ISSUE TITLE
Update documentation to accommodate dev version of DBI

### ISSUE THREAD

**Issue by krlmlr** [imanuelcostigan/RSQLServer#173]
### Expected behaviour

`R CMD check` succeeds with dev version of DBI.

### Actual behaviour

`R CMD check` fails with the following output:

```
❯ checking for missing documentation entries ... WARNING
  Undocumented S4 methods:
    generic 'dbExistsTable' and siglist 'SQLServerConnection,ANY'
    generic 'dbRemoveTable' and siglist 'SQLServerConnection,ANY'
    generic 'dbWriteTable' and siglist 'SQLServerConnection,ANY'
  All user-level objects in a package (including S4 classes and methods)
  should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```

### Steps to reproduce behaviour

- Install dev version of DBI from https://github.com/r-dbi/DBI
- Run `R CMD check` on *RSQLServer*

### Additional info

Because DBI changes the way it defines some generics, the documentation in *pool* needs to be updated. Unfortunately I don't see a workaround in DBI itself. Sorry for the inconvenience.

**Comment by Hong-Revo** [comment]
I don't think @imanuelcostigan is actively updating this package any more, possibly since the need for it has declined since dplyr/dbplyr now natively support SQL Server.
