### ISSUE TITLE
Use working example in README

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#22]
See comment to #3. 

@jangorecki: are you be able to send through a pull request per your suggestion. I would suggest reworking the README file such that it makes use of the AdventureWorks2012 Azure hosted DB.

**Comment by jangorecki** [comment]
I was unable to connect to those connection details with your package while it was working with RODBC.

**Comment by imanuelcostigan** [comment]
@jangorecki See message to 8a1b542. Works for me with latest on master.

**Comment by jangorecki** [comment]
@imanuelcostigan confirm it is working now, thanks for update and fix

**Comment by imanuelcostigan** [comment]
Update README's dplyr section
