### ISSUE TITLE
Add sample SQL Server database for testing

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#3]
With `library(hflights)` data set?

**Comment by imanuelcostigan** [comment]
See Hadley's changes to RMySQL which connects to a Google hosted MySQL database. Does Azure provide such hosting facilities for SQL Server instances?

**Comment by jangorecki** [comment]
> Does Azure provide such hosting facilities for SQL Server instances?

Yes it does. [Here](http://www.sqlrelay.co.uk/downloads/slides/2014/Steph%20Locke%20-%20R_intro_markdown.html#10) are the connection details.
Please reopen and extend docs for live examples. Thanks

**Comment by imanuelcostigan** [comment]
@jangorecki Thanks for the link. It isn't a free MSFT supported instance but rather one paid for and [provided by a member of SQL Server community](http://sqlblog.com/blogs/jamie_thomson/archive/2012/03/27/adventureworks2012-now-available-to-all-on-sql-azure.aspx). I can't rely on this. In the dev version, you can specify SQL server details in ~/sql.yaml. If you include one with the name "TEST", the limited test cases that I have specified will work.

**Comment by jangorecki** [comment]
@imanuelcostigan Then maybe you can put a working example here in the comment only?
