### ISSUE TITLE
copy_to not work

### ISSUE THREAD

**Issue by bluaze** [imanuelcostigan/RSQLServer#39]
here is the error message

Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for BEGIN TRANSACTION (The executeQuery method must return a result set.)

**Comment by imanuelcostigan** [comment]
Still working through the dplyr backend. Development is continuing the [feature-dplyr-backend branch](https://github.com/imanuelcostigan/RSQLServer/tree/feature-dplyr-backend)
