### ISSUE TITLE
Remove dplyr:: prefixes

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#42]
The functions that make qualified calls to dplyr functions shouldn't work unless dplyr is first attached. This means that:

1. RSQLServer's dplyr backend will **not** work unless dplyr itself is attached. 
2. This also means that `library(RSQLServer)` should rarely if ever be called. Should be installed, then call `library(DBI)` and `library(dplyr)` to use the SQL Server DBI backend and dplyr backend respectively.

**Comment by imanuelcostigan** [comment]
Also remove calls to non-exported dplyr functions called by the prefix `dplyr:::`

**Comment by shrektan** [comment]
Hello, I like the idea, however I'm curious about the way you plan to implement it. That is, without explicitly attach the package, how will R know to call the function of your package?




发自网易邮箱大师
在2015年07月19日 11:44，Imanuel Costigan 写道:

The functions that make qualified calls to dplyr functions shouldn't work unless dplyr is first attached. This means that:

RSQLServer's dplyr backend will not work unless dplyr itself is attached.
This also means that library(RSQLServer) should rarely if ever be called. Should be installed, then call library(DBI) and library(dplyr) to use the SQL Server DBI backend and dplyr backend respectively.

**Comment by imanuelcostigan** [comment]
@shrektan see my comments above. RSQLServer is effectively a backend. It shouldn't ever be attached to your session with `library(RSQLServer)`. 

You should only need to install it and then call:

1. `library(DBI)` to get DBI generics loaded if you wish to use `dbConnect()` etc. DBI will know where to dispatch your call to based on the driver you pass to dbConnect. The call to the RSQLServer driver should be qualified (`RSQLServer::SQLServer()`).
2. `library(dplyr)` if you wish to use dplyr backend. If you wish to add a SQL Server `src`. simply qualify the call to `RSQLServer::src_sqlserver`.
