### ISSUE TITLE
SQL.YAML Location

### ISSUE THREAD

**Issue by mrdevlar** [imanuelcostigan/RSQLServer#57]
Despite having sql.yaml in what I think is ~/, or the home directory. An attempt to connect returns:
```
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", url, properties) : 
  java.sql.SQLException: Unknown server host name 'AW'.
```
Is there any way to determine where this yaml file should be to prevent this?

**Comment by imanuelcostigan** [comment]
See `?SQLServer`. It will look for the YAML file in the following location by default: `Sys.getenv("HOME")`
