### ISSUE TITLE
Possibility of adding regular ODBC support?

### ISSUE THREAD

**Issue by jjcad** [imanuelcostigan/RSQLServer#58]
This repo was linked to from http://blog.revolutionanalytics.com/2015/10/the-dplyrxdf-package.html, which got me interested since it is insinuated that dplyr backend for SQL Server is supposed to be coming out with in a future version of this package. However I notice the use of Java-based drivers.  Some organizations (my own included) do not permit Java on Windows Servers, which is where we currently also have our enterprise R installation.  For database access we currently make use of RODBC with the normal ODBC drivers provided by Microsoft.  Does the possibility exist to add support for the MS ODBC driver?  If so, I'd be interested in lending support.

**Comment by imanuelcostigan** [comment]
The dplyr backend is available if you install using `install_github("imanuelcostigan/RSQLServer")`.

You are welcome to fork this package and use a different driver. I have no plans of doing so.
