### ISSUE TITLE
using ms driver instead of jtds

### ISSUE THREAD

**Issue by ying-w** [imanuelcostigan/RSQLServer#59]
Is it possible to use RSQLServer with the [MS JDBC driver](http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774) rather than jTDS? Asking this because I want to test the performance difference between MS driver and jTDS.

**Comment by imanuelcostigan** [comment]
No. You are welcome to fork the project and implement the MS drivers.
