### ISSUE TITLE
src_sqlserver not found

### ISSUE THREAD

**Issue by bketterer** [imanuelcostigan/RSQLServer#61]
I apologize in advance if I'm posting this question in the wrong area.

Using the dbConnect approach, I can dbGetInfo, dbReadTable, etc. using:
con <- dbConnect(RSQLServer::SQLServer(), ...

But when I try the recommended approach so I can use the database with dplyr, I get an error. 
con <- RSQLServer::src_sqlserver(...

'src_sqlserver' is not an exported object from 'namespace:RSQLServer'

Any idea what I'm doing wrong? Is src_sqlserver not supported anymore? I think I have a simple misunderstanding of something but I can't figure out what it is.

Thanks

**Comment by imanuelcostigan** [comment]
Can you please provide the result of `devtools::session_info()`

**Comment by bketterer** [comment]
This is probably more of a detailed response than you were expecting but I really appreciate the help and don't want to waste your time. Thanks again! - Bill

[RSQLServer_Test.pdf](https://github.com/imanuelcostigan/RSQLServer/files/69986/RSQLServer_Test.pdf)

> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, mingw32             
 ui       RStudio (0.99.486)          
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2015-12-22                  

Packages --------------------------------------------------------------------------------------------------------------
 package    * version date       source                            
 assertthat   0.1     2013-12-06 CRAN (R 3.2.1)                    
 DBI        * 0.3.1   2014-09-24 CRAN (R 3.2.0)                    
 devtools   * 1.9.1   2015-09-11 CRAN (R 3.2.3)                    
 digest       0.6.8   2014-12-31 CRAN (R 3.2.0)                    
 dplyr      * 0.4.3   2015-09-01 CRAN (R 3.2.2)                    
 htmltools    0.2.6   2014-09-08 CRAN (R 3.2.0)                    
 knitr        1.11    2015-08-14 CRAN (R 3.2.2)                    
 magrittr     1.5     2014-11-22 CRAN (R 3.2.1)                    
 memoise      0.2.1   2014-04-22 CRAN (R 3.2.0)                    
 R6           2.1.1   2015-08-19 CRAN (R 3.2.2)                    
 Rcpp         0.12.2  2015-11-15 CRAN (R 3.2.3)                    
 rJava      * 0.9-7   2015-07-29 CRAN (R 3.2.2)                    
 RJDBC        0.2-5   2014-12-19 CRAN (R 3.2.3)                    
 rmarkdown    0.9     2015-12-22 CRAN (R 3.2.3)                    
 rsconnect    0.4.1.4 2015-11-17 Github (rstudio/rsconnect@fcac892)
 RSQLServer * 0.1.1   2014-10-10 CRAN (R 3.2.3)                    
 rstudioapi   0.4.0   2015-12-09 CRAN (R 3.2.3)                    
 yaml         2.1.13  2014-06-12 CRAN (R 3.2.0)

**Comment by imanuelcostigan** [comment]
This is an easy response: `RSQLServer::src_sqlserver` is only available in the unreleased version of this package. Use `devtools::install_github("imanuelcostigan/RSQLServer")` to install dev version

**Comment by bketterer** [comment]
I'm close! When I run

test <- RSQLServer::src_sqlserver(server=xxx, databse=xxx, user=xx, password=xx)

I get an error message that says user and password are unused arguments.

If I remove user and password, I get the following error:

Error in rJava::.jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", url,  : 
  java.sql.SQLException: I/O Error: SSO Failed: Native SSPI library not loaded. Check the java.library.path system property.

 For what it's worth, if I try to connect using dbConnect when RSQLServer dev version is loaded, it too says user and password are unused arguments (which did not happen when the prod version is loaded).

Thanks for your help and patience!

**Comment by imanuelcostigan** [comment]
Please refer to the help file associated with src_sqlserver.
