### ISSUE TITLE
Failed to install due to the breaking changes in dplyr of `src_translate_env`

### ISSUE THREAD

**Issue by shrektan** [imanuelcostigan/RSQLServer#64]
This package can't be installed due to the breaking changes in `dplyr`, see [News.md in dplyr](https://github.com/hadley/dplyr/blob/053a996cb12aeb8c0ac305cbe268c5590a4ea3e5/NEWS.md)

> src_translate_env() has been replaced by sql_translate_env() which should have methods for the connection object.

**Comment by imanuelcostigan** [comment]
Working on revamping dplyr backend to support extensive dplyr internal changes with release v0.5.0. No ETA at this stage.

**Comment by imanuelcostigan** [comment]
Fixed this particular issue. But more extensive dplyr backend changes required.

**Comment by shrektan** [comment]
Thanks!
