### ISSUE TITLE
Error looking for some dependance in dplyr?

### ISSUE THREAD

**Issue by rtjohn** [imanuelcostigan/RSQLServer#72]
### Expected behavior
Successful loading of package.

### Actual behaviour
Error : object ‘src_translate_env’ is not exported by 'namespace:dplyr'

### Steps to reproduce behaviour
require(RSQLServer)
Loading required package: reshape

Attaching package: ‘reshape’

The following objects are masked from ‘package:tidyr’:

    expand, smiths

The following object is masked from ‘package:lubridate’:

    stamp

The following object is masked from ‘package:dplyr’:

    rename

The following object is masked from ‘package:Matrix’:

    expand

The following objects are masked from ‘package:plyr’:

    rename, round_any

Loading required package: RSQLServer
Error : object ‘src_translate_env’ is not exported by 'namespace:dplyr'

**Comment by rtjohn** [comment]
Appears 'str_translate_env' is now called 'src-test' ?? Still investigating.

**Comment by chrishaid** [comment]
@rtjohn  Look at issue #68.  `dplyr 0.5` has updated how that package handles backend connections.  The current solution is to downgrade dplyr to 0.4.3.  There's an example of how to do so in issue #68.

**Comment by imanuelcostigan** [comment]
This particular artefact was also in #64
