### ISSUE TITLE
Java Class not Found Exception for com/github/RSQLServer/MSSQLResultPull on OS X El Capitan

### ISSUE THREAD

**Issue by chrishaid** [imanuelcostigan/RSQLServer#77]
### Expected behaviour
Query results returned when connected to a SQL server database from OS X using RSQLServer

### Actual behaviour
Fetching the results raises `java.lang.ClassNotFoundException` exception when `rJava::.jnew()` is called. It seems that the `com/github/RSQLServer/MSSQLResultPull` class can't be found even though it is in `java/` directory installed with the package.

### Steps to reproduce behaviour

I'm running into a problem on OS X El Capitan where I can connect to a SQL Server database but the `fetch()` method is failing because `rJava::.jnew()` cannot find the `com/github/RSQLServer/MSSQLResultPull` class. 

It's pretty easy to recreate on my machine using the AW data base.

Assuming you have the `sql.yaml` file in your home directory, making and verifying the connection is straighforward:

``` r
library(DBI)

aw <- dbConnect(RSQLServer::SQLServer(), "AW", database = 'AdventureWorks2012')

head(dbListTables(aw), 10)
```

    ##  [1] "ATest"                 "AWBuildVersion"       
    ##  [3] "bigProduct"            "bigTransactionHistory"
    ##  [5] "DatabaseLog"           "ErrorLog"             
    ##  [7] "spt_values"            "SqlFamily"            
    ##  [9] "Department"            "Employee"

Here's where the problem is:

``` r
res <- dbSendQuery(aw, 'SELECT TOP 10 * FROM HumanResources.Department')

# Wrapping with try to create show error
dbFetch(res)
```

    ## Error in rJava::.jnew("com/github/RSQLServer/MSSQLResultPull", rJava::.jcast(res@jr, : java.lang.ClassNotFoundException

``` r
devtools::session_info()
```

    ## Session info --------------------------------------------------------------

    ##  setting  value                       
    ##  version  R version 3.3.1 (2016-06-21)
    ##  system   x86_64, darwin13.4.0        
    ##  ui       X11                         
    ##  language (EN)                        
    ##  collate  en_US.UTF-8                 
    ##  tz       America/Chicago             
    ##  date     2016-07-14

    ## Packages ------------------------------------------------------------------

    ##  package    * version date      
    ##  assertthat   0.1     2013-12-06
    ##  DBI        * 0.4-2   2016-07-14
    ##  devtools     1.12.0  2016-06-24
    ##  digest       0.6.9   2016-01-08
    ##  dplyr        0.5.0   2016-06-24
    ##  evaluate     0.9     2016-04-29
    ##  formatR      1.4     2016-05-09
    ##  htmltools    0.3.5   2016-03-21
    ##  knitr        1.13    2016-05-09
    ##  magrittr     1.5     2014-11-22
    ##  memoise      1.0.0   2016-01-29
    ##  purrr        0.2.2   2016-06-18
    ##  R6           2.1.2   2016-01-26
    ##  Rcpp         0.12.5  2016-05-14
    ##  rJava        0.9-9   2016-07-12
    ##  rmarkdown    1.0     2016-07-08
    ##  RSQLServer   0.2.099 2016-07-14
    ##  stringi      1.1.1   2016-05-27
    ##  stringr      1.0.0   2015-04-30
    ##  tibble       1.1     2016-07-04
    ##  withr        1.0.2   2016-06-20
    ##  yaml         2.1.13  2014-06-12
    ##  source                                     
    ##  CRAN (R 3.3.0)                             
    ##  Github (rstats-db/DBI@9202aa5)             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  local                                      
    ##  CRAN (R 3.3.0)                             
    ##  Github (imanuelcostigan/RSQLServer@0b49b84)
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)                             
    ##  CRAN (R 3.3.0)

**Comment by imanuelcostigan** [comment]
Thanks for picking this up.

**Comment by imanuelcostigan** [comment]
After `install_github("imanuelcostigan/RSQLServer")` (fbe828a6), find that:

```
d> list.files("~/R-dev/RSQLServer/java")
[1] "jtds-1.2.8.jar"
```

After `install()` from root source package directory, 

```
d> list.files("~/R-dev/RSQLServer/java")
[1] "jtds-1.2.8.jar"       "MSSQLRequestPull.jar"
```

Looks like java file isn't being version controlled and hence not on Github!

**Comment by chrishaid** [comment]
Works like a charm now.  Thanks, @imanuelcostigan!
