### ISSUE TITLE
Setup Appveyor CI

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#80]
Key things to figure out:

- How to [store secret](http://www.appveyor.com/docs/how-to/secure-files)
- make sure Java runtime is found

**Comment by imanuelcostigan** [comment]
Need to set this up on a Windows machine with NuGet

**Comment by imanuelcostigan** [comment]
@Hong-Revo I don't have access to Windows desktop that will allow me to follow instructions here:
https://github.com/appveyor/secure-file. Are you able to create action this on the `feature-appveyor-80` branch?

**Comment by Hong-Revo** [comment]
I'll see what I can do. My Github install is a bit messed up right now though, unfortunately.

**Comment by Hong-Revo** [comment]
So, it looks like Nuget support for RTVS projects may be broken at the moment.

**Comment by Hong-Revo** [comment]
Package Manager doesn't understand projects without files, so I've installed secure-file from the command line

**Comment by Hong-Revo** [comment]
Actually, Appveyor should work fine without encryption. (Or it should... currently getting [build failures](https://github.com/krlmlr/r-appveyor/issues/77) on [a small test project.](https://github.com/Hong-Revo/testPkg)) Do we still want to add encryption?

**Comment by imanuelcostigan** [comment]
PR in #105

**Comment by Hong-Revo** [comment]
Turns out you don't need secure-file (and I don't know if it would work with OpenSSL-encrypted files anyway).
