### ISSUE TITLE
jTDS Driver not found on OS X or Windows 7

### ISSUE THREAD

**Issue by mattpolicastro** [imanuelcostigan/RSQLServer#9]
# Summary
dplyr-flavoured RSQLServer is unable to locate the jTDS driver included in the package on OS X (and on other *nix systems, I suspect). Given that the jTDS drivers are cross-platform, I suggest some basic platform checks to properly load the SQL Server drivers.

# Reproduction
When attempting to use the package on OS X, the following error is encountered:

```
> dbConnect(SQLServer(), server = <serverName>, database = <databaseName>, user = <user>, password = <password>)
Error in is(object, Cl) : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': Error in .jfindClass(as.character(driverClass)[1]) : class not found
```

Similarly, when the `SQLServer()` driver is invoked with the Package name, the same error is returned:

```
> RSQLServer::SQLServer()
Error in .jfindClass(as.character(driverClass)[1]) : class not found
```

However, these same commands on Windows run without error.

# Solution
As described above, I believe it's a simple cross-platform bug (filesystem formatting and escapes vary). I've used the following pattern to circumvent similar issues in the past:

```
if(Sys.info()['sysname'] == "Darwin"){
  JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver",
       "~/Downloads/sqljdbc_4.0/enu/sqljdbc4.jar")
} else if(Sys.info()['sysname'] == "Windows"){
  JDBC("com.microsoft.sqlserver.jdbc.SQLServerDriver",
            "C:\\Program Files\\Microsoft JDBC Driver 4.0 for SQL Server\\sqljdbc_4.0\\enu\\sqljdbc4.jar")
} else {
  error("Sorry: your platform is not currently supported.")
}
```

`Sys.info()` is part of the base package and does not incur additional dependencies. "Darwin" refers to the old [open-source variant of OS X](http://en.wikipedia.org/wiki/Darwin_%28operating_system%29)—I don't believe it would work for other *nix systems.

**Comment by mattpolicastro** [comment]
Taking some time to look at it—the `jdbc_class_path` function seems to be the origin of the error:

```
> file.path(system.file('java', package = 'RSQLServer'), 'jtds-1.3.1.jar')
[1] "/Library/Frameworks/R.framework/Versions/3.1/Resources/library/RSQLServer/java/jtds-1.3.1.jar"
> drv <- JDBC(driverClass = "net.sourceforge.jtds.jdbc.Driver", classPath = file.path(system.file('java', package = 'RSQLServer'), 'jtds-1.3.1.jar'))
Error in .jfindClass(as.character(driverClass)[1]) : class not found
```

 I suspect it may have to do with specifying absolute vs. relative file locations in OS X. Looking into alternatives/fixes.

**Comment by mattpolicastro** [comment]
Tried loading the driver directly with no success:

```
> drv <- JDBC("net.sourceforge.jtds.jdbc.Driver", "~/Downloads/jtds-1.3.1.jar/")
Error in .jfindClass(as.character(driverClass)[1]) : class not found

```

Did some more sniffing and I no longer think it's a filesystem problem—seems to be a problem with [Java classpaths.](http://jtds.sourceforge.net/faq.html#classNotFound) Perhaps fixed with something [like this?](http://stackoverflow.com/questions/3104040/how-to-set-the-classpath-for-rjava-in-r)

Unfortunately, Java internals are beyond my ken—hopefully someone else can pick up for me.

**Comment by imanuelcostigan** [comment]
I'll test on my OSX machine later in the week. In meantime, a few questions:

- What version of OSX you running?
- What version of Java is installed on your OS?
- What happens when you run `rJava::.jinit()` (copy and paste into R session)? It should start a JVM quietly and print nothing to the REPL.
- Can you please copy and paste result of `sessionInfo()`?
- Can you please run `RSQLServer::SQLServer()` again and then immediately after that fails run `traceback()`? Please copy and paste the traceback's output.

Thanks!

**Comment by mattpolicastro** [comment]
* OSX 10.10.1 (14B25)
* JRE 8u25
* `rJava::.jinit()` works as expected—quietly loads.
* `sessionInfo()` from a fresh session:
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] rJava_0.9-6 tools_3.1.2
```
* `traceback()` from running `RSQLServer::SQLServer()`:
```
5: stop("class not found")
4: .jfindClass(as.character(driverClass)[1])
3: is.jnull(.jfindClass(as.character(driverClass)[1]))
2: RJDBC::JDBC(driverClass = "net.sourceforge.jtds.jdbc.Driver", 
       classPath = jdbc_class_path())
1: RSQLServer::SQLServer()

**Comment by imanuelcostigan** [comment]
So:

1. Not the name of the jar file. Tried that and it still didn't find the driver class.
2. This [rJava issue thread](https://github.com/s-u/rJava/issues/9) might be useful. 
3. This [thread](https://www.java.net/node/694482) on what is needed to compile jTDS also looks useful

**Comment by mattpolicastro** [comment]
Understood. Thank you for taking the time and for tolerating my somewhat overzealous investigation.

**Comment by imanuelcostigan** [comment]
I'll close once I'm confident this isn't an RSQLServer thing

**Comment by imanuelcostigan** [comment]
Tracing through call stack (as per above) and debugging `RJDBC::JDBC()`:

1. `classPath` is defined to be: `*/RSQLServer/inst/java/jtds-1.3.1.jar`
2. `.jinit(classPath)` returns `0` (successful)
3. After the JVM is initialised with this classPath, I immediately run `.jclassPath() which "returns a vector containg the current entries in the class path" (from help file):

```R
# [1] "/Library/Frameworks/R.framework/Versions/3.1/Resources/library/rJava/java"          
# [2] "*/RSQLServer/java"                                            
# [3] "*/RSQLServer/inst/java/jtds-1.3.1.jar"                        
# [4] "/Library/Frameworks/R.framework/Versions/3.1/Resources/library/RJDBC/java/RJDBC.jar"
```

But `.jaddClassPath(system.file("java", "RJDBC.jar", package = "RJDBC"))` fails with message:

> Error in .jfindClass(as.character(driverClass)[1]) : class not found

where `driverClass` is "net.sourceforge.jtds.jdbc.Driver"

**Comment by imanuelcostigan** [comment]
Tried forcing R to look at JRE 6 rather than 8 using [rJava install notes](http://rforge.net/rJava/) and [R-admin](http://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Java-_0028OS-X_0029) tips. Same issue.

**Comment by imanuelcostigan** [comment]
I've marked as wontfix for the time being. I think this is most like something to do with OS X and Java. Like you said, works on Windows. Will make the package Windows only until such time as jTDS is updated and then I'll look into it again.

**Comment by mattpolicastro** [comment]
Thanks for all the work/help. I may continue experimenting—if I make any significant headway I'll provide updates.

**Comment by imanuelcostigan** [comment]
I'm now getting the same error on Windows 7 x64. Same problem with JRE1.7 and JRE1.8. Perhaps interestingly, I can run `helloJavaWorld::helloJavaWorld()`

**Comment by imanuelcostigan** [comment]
This is doing my head in. On a different Win 7 machine, `SQLServer()` executes fine. For future reference:

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RSQLServer_0.2 rJava_0.9-6    DBI_0.3.1      httr_0.6.1    

loaded via a namespace (and not attached):
 [1] assertthat_0.1 bitops_1.0-6   devtools_1.7.0 dplyr_0.4.1    magrittr_1.5  
 [6] parallel_3.1.2 Rcpp_0.11.4    RCurl_1.95-4.5 RJDBC_0.2-5    roxygen2_4.1.0
[11] stringr_0.6.2  tools_3.1.2  
```

and 

![image](https://cloud.githubusercontent.com/assets/2107580/6207369/466604b4-b5f4-11e4-94d6-89a40b51d82e.png)

**Comment by imanuelcostigan** [comment]
This issue has now disappeared from my test machine. Will close for time being.
