### ISSUE TITLE
Use DBI's dbWithTransaction where possible

### ISSUE THREAD

**Issue by imanuelcostigan** [imanuelcostigan/RSQLServer#90]
Added in v0.4-3 with `dbBreak()`

**Comment by imanuelcostigan** [comment]
Possibly related: #102 and #106

**Comment by r2evans** [comment]
The examples of `dbWithTransaction` use `dbExecute`, from which I infer that this may be more of a user-level function. I think it makes sense in `dbWriteTable` but not necessarily within `dbSendQuery` or `dbSendStatement`. Is that right? (In fact, `dbWT` seems to be the *only* place I can find in your code where I think it makes much sense, if I'm interpreting things correctly.)

**Comment by imanuelcostigan** [comment]
See 4da2de5
