### ISSUE TITLE
question: long-term intent of this?

### ISSUE THREAD

**Issue by r2evans** [imanuelcostigan/RSQLServer#98]
Not an issue, more of a question.

## 1. Do you have concerns about the future of accessing SQL Server from R?

It appears that jTDS has not been updated in almost 2 years, with the last commit in Nov 2014 and last release in 2013. One of the (last?) developers stated he doesn't ["see how to continue work"](https://sourceforge.net/p/jtds/discussion/129584/thread/050f9892/), citing that "Microsoft drivers are much better now" (same source).

There were questions about its [Java 8 "certification status"](https://sourceforge.net/p/jtds/discussion/104389/thread/b4cd997d/) (from which I infer "tested and robust under java 8", not whether it is legally certified). Since Java 7 [no longer receives public updates](http://www.oracle.com/technetwork/java/javase/eol-135779.html#Java7-end-public-updates), I am believing that Java 8 is preferred, both for security and for future maintainability. (I don't know the language-specific consequences of 7 versus 8.)

The only alternative (in R) for accessing SQL Server currently appears to be a combination of unixODBC and MS SQL Server ODBC driver for linux. There are some issues with the ODBC interface (that may be affecting TDS-stuff in general, frankly, such as the "ntext" versus "nvarchar(max)" problem I mentioned in #97).

I have read that you have worked some with krlmlr for DBI-0.5 (an effort I applaud), and I know your milestones include improving the driver to support that. From this it appears that there is every intention to keep this for as long as jTDS works and SQL Server maintains compatibility.

## 2. Where in your package can you use some help?

I'm not a java developer, and though I have intentions of learning enough about rJava to work on another package (interface to Kafka; rkafka is broken/unmaintained), I don't think it's a selling point. I'm strong enough in R that I think I can help out with PRs and/or patches.

**Comment by imanuelcostigan** [comment]
The package's dependence on jTDS is quite concerning (indeed, even this package's dependence on rJava package is concerning). I have no intention of giving up on this project in near / medium term. You can see work on DBI 0.5 on associated branch.

An alternative driver, [FreeTDS](http://www.freetds.org), looks quite promising, is well supported, [cross-platform compatible](http://www.freetds.org/userguide/osissues.htm), and probably a lot faster than using jTDS, but I haven't ever had to link a C-based library into an R package. Maybe one day I'll roll up my sleeve and give it a go, but not anytime soon. An outside chance is Microsoft open sourcing its drivers, but I'm not holding my breath.

I'd be very keen for some support thanks! Submitting bugs and PRs are very welcome. For example, you are welcome to submit a PR with your [patch](https://github.com/imanuelcostigan/RSQLServer/issues/96#issuecomment-241582323) to #96. Please take a look at the [PR guidelines](https://github.com/imanuelcostigan/RSQLServer/blob/master/CONTRIBUTING.md)

**Comment by r2evans** [comment]
Thanks for the answer! I'll work on #96. Do you recommend I fork off of "feature-dbi-0_5" or "master"?

I've been looking into linking a C library ([`librdkafka`](https://github.com/edenhill/librdkafka)) into an R package; there are a few good model packages for seeing how it's done, though since I'm not an active and proficient C/C++ programmer, I'm a little slower at it than most.

I'm aware of FreeTDS ([github](https://github.com/FreeTDS/freetds)) and am using it on linux for my ODBC driver, and as much as ODBC is supposed to be great, I don't think it's quite the panacea it was made out to be (`sqlSave` for one, but I know that's primarily `RODBC`'s problem). From that github site, it looks like all that may be needed is in `src/tds` (the other dirs provide layers on top of it, such as `src/odbc`).

Several of the issues are fairly heavy in Java, so I'll defer. Some seem like they could be resolved completely in R (#52, #60, and #90, to name three), so I might be able to submit for them, though the body of the issues are a little sparse. Is there any other portion of the R code that is not in an issue? (For instance, [`jdbcToRType`](https://github.com/imanuelcostigan/RSQLServer/blob/master/R/jdbc-methods.R#L51) has a lot of constants being defined on each call, these could be formalized as a global variable similar to [`OPTIONAL_JTDS_FIELDS`](https://github.com/imanuelcostigan/RSQLServer/blob/master/R/Utils.R#L20). Minor certainly, just a thought, not a nit-pick!)

BTW: are you running a full-up SQL Server instance for unit-testing, or do you have [SQL Server Express](https://www.microsoft.com/en-us/cloud-platform/sql-server-editions-express) (and is it sufficient for tests)? (I'm in an unenviable position of using all three of SQL Server (on a client's network), SQLite (for quick development), and a non-Windows server running Postgres. My only option for testing this at the moment is to ssh-tunnel to my client's server, not exactly sustainable or even encouraged.)
